\context ChordNames \chords {
	\set majorSevenSymbol = \markup { "maj7" }
	\set chordChanges = ##t

	% intro
	b1:m b1:m
	g1 fis1

	% vengan y subamos...
	b1:m e1:m g2 a2 b1:m
	g1 a1 fis1:sus4 fis1
	b1:m e1:m g2 a2 b1:m
	g1 a1 b1:m b1:m

	% la ley saldra...
	a1 fis1 b1:m g1
	e1:m fis1 b2:m a2 g1
	a1 fis1 b1:m g1
	e1:m fis1 b1:m fis1

	% vengan y subamos (final)...
	b1:m e1:m g2 a2 b1:m
	g1 a1 b1:m b1:m
	g1 a1 b1:m b1:m
	b1:m
}
